steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcpdevops', '.']

images:
- 'gcr.io/$PROJECT_ID/gcpdevops'

# 👇 This line is what the org-policy is asking for
options:
  logging: CLOUD_LOGGING_ONLY
